import './globals.css'

export const metadata = {
  title: 'ฟาร์มเห็ดไอ้เหี้ยกี้',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg'>{children}</body>
    </html>
  )
}
